baseURL = 'https://msluyter.github.io/'
languageCode = 'en-us'
title = "Mike Sluyter's Blog"
theme = 'PaperMod'

[params]
  defaultTheme = 'auto'
  showReadingTime = true
  showShareButtons = false
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true

  [params.homeInfoParams]
    Title = "Hi there"
    Content = "Welcome to my blog."

  [[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/msluyter'

[menu]
  [[menu.main]]
    identifier = 'posts'
    name = 'Posts'
    url = '/posts/'
    weight = 10
  [[menu.main]]
    identifier = 'archives'
    name = 'Archives'
    url = '/archives/'
    weight = 20
  [[menu.main]]
    identifier = 'search'
    name = 'Search'
    url = '/search/'
    weight = 30

[outputs]
  home = ['HTML', 'RSS', 'JSON']
